pais= input("Ingrese un pais ")

# if pais=="mexico" or pais=="españa" or pais=="colombia":
#     print(f"{pais} es una pais de habla hispana")
# else:
#     print(f"{pais}no es pais de habla hispana")
  



# if not pais=="mexico" or pais=="colombia":
     
#      print(f"{pais} no es un pais de habla hispana")
# else:
#     print(f"{pais} si es un pais de habla hispana")





if pais!="mexico" and pais!="españa" and pais!="colombia":
    print(f"{pais} no es un pais de habla hispana")

else:
    print(f"{pais} si es una pais de habla hispana")
